version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VITE_SERVER_PORT=${VITE_SERVER_PORT}
    ports:
      - ${VITE_SERVER_PORT}:${VITE_SERVER_PORT}
